class Main
{
public static void main(String args[])
{

try
{
int a=200/0;
System.out.println(a);
}


catch(NullPointerException e)
{
System.out.println(e);
}

finally
{
System.out.println("finally block is always executed");   
}
System.out.println("rest of code");
}
}


output:
finally block is always executed
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at Main.main(Main.java:8)
